export const GET_CART_LOADING = "GET_CART_LOADING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

// remove
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
