export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";

export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

//KURTI
export const GET_KURTI_DISCOUNT = "GET_KURTI_DISCOUNT";
export const GET_KURTI_FILTERED = "GET_KURTI_FILTERED";
export const GET_KURTI_SUCESS = "GET_KURTI_SUCESS";

///JEANS
export const GET_JEANS_SUCESS = "GET_JEANS_SUCESS";
export const GET_JEANS_DISCOUNT = "GET_JEANS_DISCOUNT";
export const GET_JEANS_FILTERED = "GET_JEANS_FILTERED";

//SHIRT
export const GET_SHIRTS_SUCESS = "GET_SHIRTS_SUCESS";
export const GET_SHIRTS_DISCOUNT = "GET_SHIRTS_DISCOUNT";
export const GET_SHIRTS_FILTERED = "GET_SHIRTS_FILTERED";

//TOPS
export const GET_TOPS_SUCESS = "GET_TOPS_SUCESS";
export const GET_TOPS_DISCOUNT = "GET_TOPS_DISCOUNT";
export const GET_TOPS_FILTERED = "GET_TOPS_FILTERED";

//SEARCH
export const GET_SEARCH = "GET_SEARCH";
